# Generated by Django 3.1.7 on 2021-06-17 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='SecondName')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Администратор')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувача',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Character_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва характеристики')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Характеристику',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Character_value_v',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Опис характеристики')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_value', to='shop.character_value', verbose_name='Назва характеристики')),
            ],
            options={
                'verbose_name': ' Значение характеристики',
                'verbose_name_plural': 'Значение характеристик',
            },
        ),
        migrations.CreateModel(
            name='Order_s_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name="Им'я")),
                ('last_name', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('patronymic', models.CharField(max_length=150, verbose_name='По батькові')),
                ('telephone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('region', models.CharField(max_length=150, verbose_name='Область')),
                ('city', models.CharField(max_length=150, verbose_name='Місто')),
                ('delivery', models.CharField(max_length=150, verbose_name='Спосіб доставки')),
                ('post', models.CharField(max_length=150, verbose_name='Номер відділення пошти')),
                ('payment', models.CharField(max_length=150, verbose_name='Спосіб оплати')),
                ('total', models.IntegerField(default=0, verbose_name='Вартість замовлення')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час замовлення')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('picture', models.ImageField(upload_to='product/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('discount', models.BooleanField(default=False, verbose_name='Знижка')),
                ('inStock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('incart', models.BooleanField(default=False)),
                ('summaryPrice', models.IntegerField(default=0)),
                ('quantit', models.IntegerField(default=1)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('text', models.TextField(max_length=5000, verbose_name='Коментарий')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Был написан')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.review', verbose_name='Отзыв на коментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usreview', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='shop.character_value', verbose_name='Название хар')),
                ('chararacter_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.character_value_v', verbose_name='Название характеристики')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': ' Значение характеристики',
                'verbose_name_plural': 'Значение характеристик',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='shop.product', verbose_name='Слайди')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайди',
            },
        ),
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість')),
                ('price', models.CharField(default=None, max_length=150, verbose_name='Ціна')),
                ('product_id', models.IntegerField(default=0, verbose_name='Id товару')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order_s_info')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usproduct', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
    ]
